[options]
library = "LightDM"
version = "1"
min_cfg_version = "1"
target_path = "."
girs_directories = ["../../lightdm-gir-files"]
work_mode = "sys"
single_version_file = true

external_libraries = ["GLib", "Gio", "GObject"]
